version: '3.1'

services:
  bankdb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
