### Send get request to get all users card
GET http://0.0.0.0:9999/getCards?userId=2 HTTP/1.1

### Send get request to get all transactions by card
GET http://0.0.0.0:9999/getTransactions?cardId=1 HTTP/1.1

### Send get request to get most paid categories
GET http://0.0.0.0:9999/getMostPaid?userId=1 HTTP/1.1

### Send get request to get most bought categories
GET http://0.0.0.0:9999/getMostOftenBought?userId=1 HTTP/1.1
